import { IndexerErrorModule } from '@injectivelabs/exceptions';
export * from './mito';
export * from './swap';
export * from './spot';
export * from './oracle';
export * from './account';
export * from './auction';
export * from './trading';
export * from './exchange';
export * from './explorer';
export * from './campaign';
export * from './spot-rest';
export * from './incentives';
export * from './derivatives';
export * from './explorer-rest';
export * from './insurance-funds';
export * from './derivatives-rest';
export * from './leaderboard-rest';
export * from './account-portfolio';
export * from './markets-history-rest';
export interface StreamStatusResponse {
    details: string;
    code: number;
    metadata: any;
}
export declare const IndexerModule: {
    Account: IndexerErrorModule.Account;
    Auction: IndexerErrorModule.Auction;
    Derivatives: IndexerErrorModule.Derivatives;
    Explorer: IndexerErrorModule.Explorer;
    InsuranceFund: IndexerErrorModule.InsuranceFund;
    Meta: IndexerErrorModule.Meta;
    Mito: IndexerErrorModule.Mito;
    Dmm: IndexerErrorModule.Dmm;
    Oracle: IndexerErrorModule.Oracle;
    Portfolio: IndexerErrorModule.Portfolio;
    Spot: IndexerErrorModule.Spot;
    Transaction: IndexerErrorModule.Transaction;
    Trading: IndexerErrorModule.Trading;
    ChronosDerivative: IndexerErrorModule.ChronosDerivative;
    ChronosSpot: IndexerErrorModule.ChronosSpot;
    ChronosMarkets: IndexerErrorModule.ChronosMarkets;
    Campaign: IndexerErrorModule.Campaign;
};
