"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChainGrpcTendermintApi = exports.ChainGrpcWasmXApi = exports.ChainGrpcWasmApi = exports.ChainGrpcTokenFactoryApi = exports.ChainGrpcStakingApi = exports.ChainGrpcPeggyApi = exports.ChainGrpcOracleApi = exports.ChainGrpcMintApi = exports.ChainGrpcInsuranceFundApi = exports.ChainGrpcIbcApi = exports.ChainGrpcGovApi = exports.ChainGrpcExchangeApi = exports.ChainGrpcDistributionApi = exports.ChainGrpcBankApi = exports.ChainGrpcAuthZApi = exports.ChainGrpcAuthApi = exports.ChainGrpcAuctionApi = void 0;
var ChainGrpcAuctionApi_1 = require("./ChainGrpcAuctionApi");
Object.defineProperty(exports, "ChainGrpcAuctionApi", { enumerable: true, get: function () { return ChainGrpcAuctionApi_1.ChainGrpcAuctionApi; } });
var ChainGrpcAuthApi_1 = require("./ChainGrpcAuthApi");
Object.defineProperty(exports, "ChainGrpcAuthApi", { enumerable: true, get: function () { return ChainGrpcAuthApi_1.ChainGrpcAuthApi; } });
var ChainGrpcAuthZApi_1 = require("./ChainGrpcAuthZApi");
Object.defineProperty(exports, "ChainGrpcAuthZApi", { enumerable: true, get: function () { return ChainGrpcAuthZApi_1.ChainGrpcAuthZApi; } });
var ChainGrpcBankApi_1 = require("./ChainGrpcBankApi");
Object.defineProperty(exports, "ChainGrpcBankApi", { enumerable: true, get: function () { return ChainGrpcBankApi_1.ChainGrpcBankApi; } });
var ChainGrpcDistributionApi_1 = require("./ChainGrpcDistributionApi");
Object.defineProperty(exports, "ChainGrpcDistributionApi", { enumerable: true, get: function () { return ChainGrpcDistributionApi_1.ChainGrpcDistributionApi; } });
var ChainGrpcExchangeApi_1 = require("./ChainGrpcExchangeApi");
Object.defineProperty(exports, "ChainGrpcExchangeApi", { enumerable: true, get: function () { return ChainGrpcExchangeApi_1.ChainGrpcExchangeApi; } });
var ChainGrpcGovApi_1 = require("./ChainGrpcGovApi");
Object.defineProperty(exports, "ChainGrpcGovApi", { enumerable: true, get: function () { return ChainGrpcGovApi_1.ChainGrpcGovApi; } });
var ChainGrpcIbcApi_1 = require("./ChainGrpcIbcApi");
Object.defineProperty(exports, "ChainGrpcIbcApi", { enumerable: true, get: function () { return ChainGrpcIbcApi_1.ChainGrpcIbcApi; } });
var ChainGrpcInsuranceFundApi_1 = require("./ChainGrpcInsuranceFundApi");
Object.defineProperty(exports, "ChainGrpcInsuranceFundApi", { enumerable: true, get: function () { return ChainGrpcInsuranceFundApi_1.ChainGrpcInsuranceFundApi; } });
var ChainGrpcMintApi_1 = require("./ChainGrpcMintApi");
Object.defineProperty(exports, "ChainGrpcMintApi", { enumerable: true, get: function () { return ChainGrpcMintApi_1.ChainGrpcMintApi; } });
var ChainGrpcOracleApi_1 = require("./ChainGrpcOracleApi");
Object.defineProperty(exports, "ChainGrpcOracleApi", { enumerable: true, get: function () { return ChainGrpcOracleApi_1.ChainGrpcOracleApi; } });
var ChainGrpcPeggyApi_1 = require("./ChainGrpcPeggyApi");
Object.defineProperty(exports, "ChainGrpcPeggyApi", { enumerable: true, get: function () { return ChainGrpcPeggyApi_1.ChainGrpcPeggyApi; } });
var ChainGrpcStakingApi_1 = require("./ChainGrpcStakingApi");
Object.defineProperty(exports, "ChainGrpcStakingApi", { enumerable: true, get: function () { return ChainGrpcStakingApi_1.ChainGrpcStakingApi; } });
var ChainGrpcTokenFactoryApi_1 = require("./ChainGrpcTokenFactoryApi");
Object.defineProperty(exports, "ChainGrpcTokenFactoryApi", { enumerable: true, get: function () { return ChainGrpcTokenFactoryApi_1.ChainGrpcTokenFactoryApi; } });
var ChainGrpcWasmApi_1 = require("./ChainGrpcWasmApi");
Object.defineProperty(exports, "ChainGrpcWasmApi", { enumerable: true, get: function () { return ChainGrpcWasmApi_1.ChainGrpcWasmApi; } });
var ChainGrpcWasmXApi_1 = require("./ChainGrpcWasmXApi");
Object.defineProperty(exports, "ChainGrpcWasmXApi", { enumerable: true, get: function () { return ChainGrpcWasmXApi_1.ChainGrpcWasmXApi; } });
var ChainGrpcTendermintApi_1 = require("./ChainGrpcTendermintApi");
Object.defineProperty(exports, "ChainGrpcTendermintApi", { enumerable: true, get: function () { return ChainGrpcTendermintApi_1.ChainGrpcTendermintApi; } });
//# sourceMappingURL=index.js.map